
[AtCoder]
  ContestID = "abc143"
  ContestURL = "https://atcoder.jp/contests/abc143"
  TaskID = "abc143_d"
  TaskName = "D - Triangles"
  TaskURL = "https://atcoder.jp/contests/abc143/tasks/abc143_d"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
