
[AtCoder]
  ContestID = "abc122"
  ContestURL = "https://atcoder.jp/contests/abc122"
  TaskID = "abc122_d"
  TaskName = "D - We Like AGC"
  TaskURL = "https://atcoder.jp/contests/abc122/tasks/abc122_d"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
