
[AtCoder]
  ContestID = "ABC181"
  ContestURL = "https://atcoder.jp/contests/ABC181"
  TaskID = "abc181_d"
  TaskName = "D - Hachi"
  TaskURL = "https://atcoder.jp/contests/ABC181/tasks/abc181_d"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
