
[AtCoder]
  ContestID = "abc186"
  ContestURL = "https://atcoder.jp/contests/abc186"
  TaskID = "abc186_b"
  TaskName = "B - Blocks on Grid"
  TaskURL = "https://atcoder.jp/contests/abc186/tasks/abc186_b"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
