
[AtCoder]
  ContestID = "abc106"
  ContestURL = "https://atcoder.jp/contests/abc106"
  TaskID = "abc106_d"
  TaskName = "D - AtCoder Express 2"
  TaskURL = "https://atcoder.jp/contests/abc106/tasks/abc106_d"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
