
[AtCoder]
  ContestID = "abc101"
  ContestURL = "https://atcoder.jp/contests/abc101"
  TaskID = "arc099_a"
  TaskName = "C - Minimization"
  TaskURL = "https://atcoder.jp/contests/abc101/tasks/arc099_a"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
